version: '3.8'

services:
  pytemplate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      # これによりルートディレクトリでpoetry run python src/test/test_feed.pyが実行できるようになる
      - PYTHONPATH=/workspace/src
